PRL-4260 - Manage orders hearing screen changes
hmcts/prl-ccd-definitions pull request #1511
Opened 2023-09-11 09:48 UTC by channa-patil

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] the `enable_keep_helm` label has been added, if the helm release should be persisted after a successful build

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-09-25 15:33 UTC, yogendraU requested changes

2023-09-25 15:33 UTC, yogendraU commented on definitions/private-law/json/ComplexTypes/HearingData/ComplexTypes.json
> +    "ElementLabel": "CAFCASS",
Please change it to Cafcass

2023-09-25 15:33 UTC, yogendraU commented on definitions/private-law/json/ComplexTypes/HearingData/ComplexTypes.json
> +    "ElementLabel": "CAFCASS Cymru",
Please change it to Cafcass Cymru

2023-09-29 14:16 UTC, channa-patil commented on definitions/private-law/json/ComplexTypes/HearingData/ComplexTypes.json
> +    "ElementLabel": "CAFCASS",
Done

2023-09-29 14:16 UTC, channa-patil commented on definitions/private-law/json/ComplexTypes/HearingData/ComplexTypes.json
> +    "ElementLabel": "CAFCASS Cymru",
Done

2024-02-13 00:00 UTC, closed without merging