initial(PRL-4467_Events_Court_Admin_submittedt):Initial commit
hmcts/prl-ccd-definitions pull request #1666
Opened 2023-11-06 16:28 UTC by JamesCutts00

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PRL-4467

### Change description ###

Changes to events for court admin when the case is in the submitted state.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-11-21 23:41 UTC, yogendraU commented
hi @JamesCutts00 , please confirm my comments with @shashisk97

2023-11-21 23:42 UTC, yogendraU requested changes

2023-11-21 23:42 UTC, yogendraU commented on definitions/private-law/json/CaseEvent/CaseEvent.json
> +    "PreConditionState(s)": "AWAITING_RESUBMISSION_TO_HMCTS;CASE_ISSUED;JUDICIAL_REVIEW;ALL_FINAL_ORDERS_ISSUED;PREPARE_FOR_HEARING_CONDUCT_HEARING;DECISION_OUTCOME",
do we need AWAITING_RESUBMISSION_TO_HMCTS state?

2023-11-21 23:42 UTC, yogendraU commented on definitions/private-law/json/CaseEvent/Order/CaseEvent-nonprod.json
> +    "PreConditionState(s)": "AWAITING_RESUBMISSION_TO_HMCTS;CASE_ISSUED;JUDICIAL_REVIEW;ALL_FINAL_ORDERS_ISSUED;PREPARE_FOR_HEARING_CONDUCT_HEARING;DECISION_OUTCOME",
do we need AWAITING_RESUBMISSION_TO_HMCTS state?

2023-11-21 23:42 UTC, yogendraU commented on definitions/private-law/json/CaseEvent/Order/CaseEvent-prod.json
> +    "PreConditionState(s)": "AWAITING_RESUBMISSION_TO_HMCTS;CASE_ISSUED;JUDICIAL_REVIEW;ALL_FINAL_ORDERS_ISSUED;PREPARE_FOR_HEARING_CONDUCT_HEARING;DECISION_OUTCOME",
do we need AWAITING_RESUBMISSION_TO_HMCTS state?

2023-11-26 22:04 UTC, yogendraU approved these changes

2023-12-08 00:33 UTC, AlokDatta approved these changes

2023-12-08 08:28 UTC, merged